### ISSUE TITLE
Installing go15 fails on Xcode 8.2 and 8.1

### ISSUE THREAD

**Issue by HaraldNordgren** [Homebrew/homebrew-versions#1499]
Preparation steps:

```
$ brew unlink go
$ brew tap homebrew/versions
$ brew update
```

Then I tried installing go15, but it fails with a reference to 'https://git.io/brew-troubleshooting':

```
$ brew install --verbose homebrew/versions/go15
==> Installing go15 from homebrew/versions
==> Downloading https://storage.googleapis.com/golang/go1.5.4.src.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.5 (Macintosh; Intel macOS 10.12.1) curl/7.49.1 https://storage.googleapis.com/golang/go1.5.4.src.tar.gz -C 0 -o /Users/travis/Library/Caches/Homebrew/go15-1.5.4.tar.gz.incomplete --connect-timeout 5 --silent
==> Verifying go15-1.5.4.tar.gz checksum
tar xzf /Users/travis/Library/Caches/Homebrew/go15-1.5.4.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.5 (Macintosh; Intel macOS 10.12.1) curl/7.49.1 https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz -C 0 -o /Users/travis/Library/Caches/Homebrew/go15--gobootstrap-10.8.tar.gz.incomplete --silent
==> Verifying go15--gobootstrap-10.8.tar.gz checksum
tar xzf /Users/travis/Library/Caches/Homebrew/go15--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
# Building C bootstrap tool.
cmd/dist
# Building compilers and Go bootstrap tool for host, darwin/amd64.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/6l
cmd/6a
cmd/6c
cmd/6g
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go
# Building packages and commands for darwin/amd64.
runtime
errors
sync/atomic
unicode
sync
io
unicode/utf8
math
bytes
bufio
syscall
strconv
time
reflect
os
strings
fmt
encoding/binary
sort
regexp/syntax
cmd/internal/goobj
cmd/internal/rsc.io/arm/armasm
cmd/internal/rsc.io/x86/x86asm
debug/dwarf
debug/elf
debug/gosym
debug/macho
debug/pe
debug/plan9obj
regexp
text/tabwriter
flag
log
hash
crypto
crypto/md5
cmd/internal/objfile
go/token
path/filepath
cmd/addr2line
go/scanner
go/ast
io/ioutil
go/parser
go/printer
os/exec
path
container/heap
cmd/cgo
go/format
cmd/fix
encoding
encoding/base64
unicode/utf16
encoding/json
encoding/xml
net/url
text/template/parse
compress/flate
hash/crc32
compress/gzip
container/list
text/template
crypto/subtle
crypto/cipher
crypto/aes
crypto/des
math/rand
go/doc
math/big
go/build
crypto/elliptic
encoding/asn1
crypto/hmac
crypto/rand
crypto/ecdsa
crypto/rc4
crypto/rsa
crypto/sha1
crypto/sha256
crypto/dsa
crypto/sha512
crypto/x509/pkix
encoding/hex
encoding/pem
runtime/cgo
mime
net/http/internal
os/signal
runtime/pprof
cmd/gofmt
cmd/nm
cmd/objdump
net
cmd/pack
cmd/pprof/internal/profile
cmd/pprof/internal/plugin
html
html/template
cmd/pprof/internal/report
cmd/pprof/internal/svg
cmd/pprof/internal/tempfile
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/pprof/internal/symbolizer
cmd/pprof/internal/symbolz
cmd/yacc
crypto/x509
net/textproto
mime/multipart
archive/tar
archive/zip
compress/bzip2
compress/lzw
hash/adler32
compress/zlib
container/ring
database/sql/driver
database/sql
encoding/ascii85
encoding/base32
encoding/csv
encoding/gob
hash/crc64
hash/fnv
image/color
image
image/color/palette
image/draw
image/gif
image/jpeg
image/png
index/suffixarray
log/syslog
math/cmplx
net/mail
os/user
crypto/tls
net/http
net/smtp
runtime/debug
runtime/race
testing
testing/iotest
testing/quick
text/scanner
cmd/go
cmd/pprof/internal/fetch
cmd/pprof
expvar
net/http/cgi
net/http/cookiejar
net/http/fcgi
net/http/httptest
net/http/httputil
net/http/pprof
net/rpc
net/rpc/jsonrpc
---
Installed Go for darwin/amd64 in /private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap
Installed commands in /private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/bin
==> ./make.bash --no-clean
##### Building Go bootstrap tool.
cmd/dist
##### Building Go toolchain using /private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap.
bootstrap/internal/obj
bootstrap/asm/internal/flags
bootstrap/compile/internal/big
bootstrap/internal/obj/arm
bootstrap/internal/obj/arm64
bootstrap/internal/obj/ppc64
bootstrap/internal/obj/x86
bootstrap/asm/internal/lex
bootstrap/internal/gcprog
bootstrap/compile/internal/gc
bootstrap/asm/internal/arch
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/link/internal/ld
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/ppc64
bootstrap/link/internal/x86
bootstrap/link
bootstrap/compile/internal/amd64
bootstrap/compile/internal/arm
bootstrap/compile/internal/arm64
bootstrap/compile/internal/ppc64
bootstrap/compile/internal/x86
bootstrap/compile
##### Building go_bootstrap for host, darwin/amd64.
runtime
failed MSpanList_Insert 0xbc63c8 0x23bdacad2d 0x0
fatal error: MSpanList_Insert
runtime stack:
runtime.MSpanList_Insert(0x92cb58, 0xbc63c8)
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Free(0x92bd80, 0xbc63c8, 0x1)
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/mheap.c:500 +0x5b
runtime.MSpan_Sweep(0xbc63c8, 0xbc6300, 0x1)
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/mgc0.c:1061 +0x6f9
runtime.MHeap_Alloc(0x92bd80, 0xa, 0x10100000000, 0xb9ae01)
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/mheap.c:240 +0x66
goroutine 1 [running]:
runtime.switchtoM()
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/asm_amd64.s:198 fp=0xc20b1572f8 sp=0xc20b1572f0
runtime.mallocgc(0x12dd0, 0x38cac0, 0xc200000000, 0xc20cb6e9a0)
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/malloc.go:199 +0x9f3 fp=0xc20b1573a8 sp=0xc20b1572f8
runtime.newarray(0x38cac0, 0x36e, 0x986000)
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/malloc.go:365 +0xc1 fp=0xc20b1573e0 sp=0xc20b1573a8
runtime.makeslice(0x322460, 0x36e, 0x36e, 0x0, 0x0, 0x0)
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/slice.go:32 +0x15c fp=0xc20b157428 sp=0xc20b1573e0
bootstrap/compile/internal/gc.Flowstart(0xc20a1adb00, 0x0, 0x62)
	/private/tmp/go15-20161230-3528-lrjqnq/go/src/cmd/compile/internal/gc/popt.go:273 +0x253 fp=0xc20b157540 sp=0xc20b157428
bootstrap/compile/internal/amd64.peep(0xc20a1adb00)
	/private/tmp/go15-20161230-3528-lrjqnq/go/src/cmd/compile/internal/amd64/peep.go:83 +0x31 fp=0xc20b1575a0 sp=0xc20b157540
bootstrap/compile/internal/gc.regopt(0xc20a1adb00)
	/private/tmp/go15-20161230-3528-lrjqnq/go/src/cmd/compile/internal/gc/reg.go:1412 +0x2f02 fp=0xc20b157a18 sp=0xc20b1575a0
bootstrap/compile/internal/gc.compile(0xc20957f8c0)
	/private/tmp/go15-20161230-3528-lrjqnq/go/src/cmd/compile/internal/gc/pgen.go:508 +0xce6 fp=0xc20b157b60 sp=0xc20b157a18
bootstrap/compile/internal/gc.funccompile(0xc20957f8c0)
	/private/tmp/go15-20161230-3528-lrjqnq/go/src/cmd/compile/internal/gc/dcl.go:1484 +0x1c4 fp=0xc20b157bd8 sp=0xc20b157b60
bootstrap/compile/internal/gc.Main()
	/private/tmp/go15-20161230-3528-lrjqnq/go/src/cmd/compile/internal/gc/lex.go:473 +0x2113 fp=0xc20b157e38 sp=0xc20b157bd8
bootstrap/compile/internal/amd64.Main()
	/private/tmp/go15-20161230-3528-lrjqnq/go/src/cmd/compile/internal/amd64/galign.go:127 +0x768 fp=0xc20b157ec0 sp=0xc20b157e38
main.main()
	/private/tmp/go15-20161230-3528-lrjqnq/go/src/cmd/compile/main.go:26 +0x121 fp=0xc20b157f98 sp=0xc20b157ec0
runtime.main()
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/proc.go:63 +0xf3 fp=0xc20b157fe0 sp=0xc20b157f98
runtime.goexit()
	/private/tmp/go15-20161230-3528-lrjqnq/go/gobootstrap/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20b157fe8 sp=0xc20b157fe0
go tool dist: FAILED: /private/tmp/go15-20161230-3528-lrjqnq/go/pkg/tool/darwin_amd64/compile -pack -o /tmp/go-tool-dist-149532252/_go_.a -p runtime -+ -asmhdr /tmp/go-tool-dist-149532252/go_asm.h /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/alg.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/arch1_amd64.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/arch_amd64.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/atomic_amd64x.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/atomic_pointer.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/cgo.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/cgocall.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/cgocallback.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/chan.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/compiler.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/complex.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/cpuprof.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/cputicks.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/debug.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/defs_darwin_amd64.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/env_posix.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/error.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/extern.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/hash64.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/hashmap.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/hashmap_fast.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/heapdump.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/iface.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/lfstack.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/lfstack_amd64.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/lock_sema.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/malloc.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mbarrier.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mbitmap.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mcache.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mcentral.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mem_darwin.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mfinal.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mfixalloc.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mgc.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mgcmark.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mgcsweep.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mgcwork.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mheap.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mprof.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/msize.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/mstats.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/netpoll.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/netpoll_kqueue.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/os1_darwin.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/os2_darwin.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/os_darwin.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/panic.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/panic1.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/parfor.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/print1.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/print1_write.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/proc.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/proc1.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/race0.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/rdebug.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/rune.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/runtime.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/runtime1.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/runtime2.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/select.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/sema.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/signal1_unix.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/signal_amd64x.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/signal_darwin.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/signal_darwin_amd64.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/signal_unix.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/sigpanic_unix.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/sigqueue.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/slice.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/softfloat64.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/sqrt.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/stack1.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/stack2.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/string.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/string1.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/stubs.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/stubs2.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/symtab.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/sys_x86.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/time.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/trace.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/traceback.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/type.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/typekind.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/typekind1.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/unaligned1.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/vdso_none.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/wbfat.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/zgoarch_amd64.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/zgoos_darwin.go /private/tmp/go15-20161230-3528-lrjqnq/go/src/runtime/zversion.go: exit status 2
==> Formula
Tap: homebrew/versions
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions/go15.rb
==> Configuration
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: af7ffaddab5edea4ed2fd3011fbcfb310a8d80c8
Core tap last commit: 34 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit nehalem
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/travis/.rvm/rubies/ruby-2.0.0-p648/bin/ruby
Java: 1.8.0_112
macOS: 10.12.1-x86_64
Xcode: 8.2
CLT: 8.1.0.0.1.1476494586
X11: 2.7.11 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
Error: homebrew/versions/go15 1.5.4 did not build
Logs:
     /Users/travis/Library/Logs/Homebrew/go15/00.options.out
     /Users/travis/Library/Logs/Homebrew/go15/01.make.bash
     /Users/travis/Library/Logs/Homebrew/go15/01.make.bash.cc
     /Users/travis/Library/Logs/Homebrew/go15/02.make.bash
     /Users/travis/Library/Logs/Homebrew/go15/02.make.bash.cc
READ THIS: https://git.io/brew-troubleshooting
```

The installation works on Xcode 8, 7.3 and 6.4.

**Comment by MikeMcQuaid** [comment]
When I migrate this formula to Homebrew/core I will either fix it or delete it. If you use it I recommend trying to submit a pull-request here to fix it before I remove it. Thanks!
